# Welcome to Jekyll!
# In addition to these settings, there is a file _data/tokens-template.yml
# that you'll want to customize for your site. It's named 'tokens' because
# that was it's original purpose, but because tokens.yml is .gitexcluded, it's
# a good place to store your site-specific data that you'd rather not have
# forked or cloned. Of course, that means you'd want to back it up elsewhere.

# Also, for your post bylines, add author info for yourself in `_data/authors.yml`.
# (Using that method instead of site.owner, in case your posts get cloned with your repo.)

# Site settings
title: Brett Stevenson
description: Developer &#x1f784; Designer &#x1f784; Student
owner:
  name: Brett Stevenson # or company name
  email: BStevensonDev@gmail.com
  url: https://brettstevenson.io
  avatar: "/assets/img/avatar.png"
first_published: 2015 # if migrating another site, the year of your first publish
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brettstevenson.io" # the base hostname & protocol for your site
disqus: brettstevenson

social_links:
  github: https://github.com/tterb
  deviantart: https://bstevenson.deviantart.com/
  dribbble: https://dribbble.com/JonSn0w
  linkedin-in: https://www.linkedin.com/in/brett-stevenson-0a035a72
  twitter: https://twitter.com/BStevensonDev
  email: /contact/

# choose where to put back and next links:
# top, bottom, both, none
navlinks: bottom

# expecting more works? mark your list as in-progress
works_in_progress: yes

# If you have custom extensions, specifically includes/_my/custom.scss,
# set this to yes
custom_extensions: no

# Contact page action
mailaction: https://formspree.io/bstevensondev@gmail.com

# Build settings
permalink: /:categories/:title.html

# permalink: /:title.html
markdown: kramdown
highlighter: rouge
sass:
 style: compressed

include: ['_pages','.htaccess']
exclude: ['vendor','_assets','node_modules','jspm_packages','Gemfile','Gemfile.lock','Gulpfile.js','.sass-lint.yml','package.json','README.md','**/fonts/*.html', '**/**/*_.*']

defaults:
  - scope:
      path: _pages
    values:
      layout: page
  - scope:
      path: _posts
    values:
      layout: post2
  - scope:
      path: _drafts
    values:
      layout: post2

# For Jekyll-SEO-tag
logo: "/assets/img/logo.png"
social:
  name: Brett Stevenson
  links:
    - https://github.com/tterb
    - https://linkedin.com/in/brett-stevenson/
    - https://twitter.com/bstevensondev
    - https://bstevenson.deviantart.com/

share:
  - facebook
  - twitter
  - google-plus
  - linkedin 
  - pinterest 
  - reddit
  - tumblr
  - pocket
  # - wordpress
  - email

plugins:
  - jemoji
  - jekyll-gist
  - jekyll-admin
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-autoprefixer
  - jekyll-redirect-from
  - jekyll-github-metadata

html_proofer:
  check_favicon: true
  check_html: true
  allow_hash_href: true
  http_status_ignore: [999,522,403]
  file_ignore:
    - /a.*regexp*/
    - a_string
    - fonts/*
    - _posts/*
    - blog/*
  url_ignore:
    - /Hyde/
    - /PlayMusic/
    - /Atomic-Design-UI/
    - /GithubCalendar/

# to initialize arrays in assignments (assign myarr = site.empty_array)
# (easier to grok than assign myarr = '' | split',')
empty_array: []
